version: "3.9"

services:

  backend:
    build: ./generateQuote-Backend
    environment:
      MONGO_URL: "mongodb://db:27017/quote"
    depends_on:
      - db
    ports:
      - "8080:8080"
      
  frontend:
    build: ./generateQuote-Frontend
    environment:
      URL_BACKEND: "localhost:8080"
    links:
      - "backend"
    ports:
      - "3000:3000"
  
  db:
    image: mongo
    volumes: 
      - data:/data/db

volumes:
  data:
